import {
  Layers,
  Grid,
  Shield,
  Umbrella,
  Sofa,
  Building2,
  Wrench,
  Hammer,
  Maximize,
  Wind,
  Sun,
  Lock,
  Droplets,
  Lightbulb,
  Store,
  AlignJustify,
  Paintbrush,
  MoveHorizontal,
  ShieldCheck,
  BoxSelect,
  VolumeX,
  Sparkles,
  Factory,
  Home,
  Circle,
  Key,
} from "lucide-react";
import { ServiceItem, ProjectItem, TeamMember, ProductItem } from "./types";

// All imageUrl values point at locally hosted, licensed assets under /public.
// No external hotlinks (Pinterest / URL shorteners / third-party sites). Where a
// service has no exact photo, the nearest genuine local image is reused as an
// illustrative thumbnail — recorded in IMAGE_SOURCES.md.

// --- SERVICES (40 Items) ---
export const services: ServiceItem[] = [
  // Glass & Mirrors
  {
    id: "g1",
    title: "Office Glass Partitions",
    category: "Glass & Mirrors",
    description: "Soundproof, 12mm toughened glass cabins for modern offices.",
    imageUrl: "/images/glass-mirrors/office-glass-partitions.png",
    icon: BoxSelect,
  },
  {
    id: "g2",
    title: "Shower Glass Enclosures",
    category: "Glass & Mirrors",
    description: "Custom frameless shower cabins with anti-scale coating.",
    imageUrl: "/images/glass-mirrors/shower-glass-enclosures.png",
    icon: Droplets,
  },
  {
    id: "g3",
    title: "12mm Toughened Glass",
    category: "Glass & Mirrors",
    description: "High-safety tempered glass for shop fronts and doors.",
    imageUrl: "/images/glass-mirrors/12mm-toughened-glass.png",
    icon: Shield,
  },
  {
    id: "g4",
    title: "Laminated Safety Glass",
    category: "Glass & Mirrors",
    description: "Double-layer safety glass for banks and high-security areas.",
    imageUrl: "/images/glass-mirrors/laminated-safety-glass.png",
    icon: ShieldCheck,
  },
  {
    id: "g5",
    title: "LED Bathroom Mirrors",
    category: "Glass & Mirrors",
    description: "Smart touch-sensor LED mirrors for luxury bathrooms.",
    imageUrl: "/images/glass-mirrors/led-bathroom-mirrors.png",
    icon: Lightbulb,
  },
  {
    id: "g6",
    title: "Frameless Glass Doors",
    category: "Glass & Mirrors",
    description:
      "Minimalist patch-fitting glass doors for commercial entryways.",
    imageUrl: "/images/glass-mirrors/frameless-glass-doors.png",
    icon: Maximize,
  },
  {
    id: "g7",
    title: "Retail Shop Fronts",
    category: "Glass & Mirrors",
    description: "Floor-to-ceiling glass display windows for malls in DHA.",
    imageUrl: "/images/glass-mirrors/retail-shop-fronts.png",
    icon: Store,
  },
  {
    id: "g8",
    title: "Glass Balcony Railings",
    category: "Glass & Mirrors",
    description: "Modern glass railings with stainless steel fittings.",
    imageUrl: "/images/glass-mirrors/glass-balcony-railings.png",
    icon: AlignJustify,
  },
  {
    id: "g9",
    title: "Glass Table Tops",
    category: "Glass & Mirrors",
    description: "Custom cut, beveled edge glass tops for dining tables.",
    imageUrl: "/images/glass-mirrors/glass-table-tops.png",
    icon: Layers,
  },
  {
    id: "g10",
    title: "Decorative Etched Glass",
    category: "Glass & Mirrors",
    description: "Laser-etched and frosted designs for privacy and art.",
    imageUrl: "/images/glass-mirrors/decorative-etched-glass.png",
    icon: Paintbrush,
  },

  // Aluminium & Steel
  {
    id: "a1",
    title: "Aluminium Sliding Windows",
    category: "Aluminium & Steel",
    description: "Smooth sliding aluminium windows for residential villas.",
    imageUrl: "/images/aluminum-steel/aluminum-office-partitions.png",
    icon: MoveHorizontal,
  },
  {
    id: "a2",
    title: "Heavy Duty Aluminium Doors",
    category: "Aluminium & Steel",
    description: "Robust aluminium doors for high-traffic areas.",
    imageUrl: "/images/advanced-solutions/automatic-sliding-doors.png",
    icon: Grid,
  },
  {
    id: "a3",
    title: "Steel Safety Grills",
    category: "Aluminium & Steel",
    description: "Decorative and secure steel grills for windows.",
    imageUrl: "/images/aluminum-steel/steel-safety-grills.png",
    icon: ShieldCheck,
  },
  {
    id: "a4",
    title: "Staircase Railings",
    category: "Aluminium & Steel",
    description: "SS and aluminium railings for stairs and terraces.",
    imageUrl: "/images/aluminum-steel/staircase-railings.png",
    icon: AlignJustify,
  },
  {
    id: "a5",
    title: "Automated Main Gates",
    category: "Aluminium & Steel",
    description: "Remote-controlled steel and aluminium main gates.",
    imageUrl: "/images/aluminum-steel/automated-main-gates.png",
    icon: Key,
  },
  {
    id: "a6",
    title: "Structural Steel Framing",
    category: "Aluminium & Steel",
    description: "Heavy steel support structures for large glass facades.",
    imageUrl: "/images/aluminum-steel/structural-steel-framing.png",
    icon: Hammer,
  },
  {
    id: "a7",
    title: "Aluminium Kitchen Cabinets",
    category: "Aluminium & Steel",
    description: "Termite-proof, long-lasting aluminium kitchen fittings.",
    imageUrl: "/images/aluminum-steel/aluminum-kitchen-cabinets.png",
    icon: BoxSelect,
  },
  {
    id: "a8",
    title: "Aluminium Office Partitions",
    category: "Aluminium & Steel",
    description: "Modular aluminium partitions with glass inserts.",
    imageUrl: "/images/aluminum-steel/aluminum-office-partitions.png",
    icon: Grid,
  },

  // UPVC
  {
    id: "u1",
    title: "UPVC Sliding Windows",
    category: "UPVC Solutions",
    description: "Energy-saving UPVC windows perfect for Lahore weather.",
    imageUrl: "/images/upvc-solutions/upvc-casement-windows.png",
    icon: MoveHorizontal,
  },
  {
    id: "u2",
    title: "UPVC Casement Windows",
    category: "UPVC Solutions",
    description: "Airtight windows offering maximum noise reduction.",
    imageUrl: "/images/upvc-solutions/upvc-casement-windows.png",
    icon: Maximize,
  },
  {
    id: "u3",
    title: "UPVC French Doors",
    category: "UPVC Solutions",
    description: "Stylish double doors opening to patios or balconies.",
    imageUrl: "/images/upvc-solutions/upvc-french-doors.png",
    icon: Grid,
  },
  {
    id: "u4",
    title: "Wood-Finish UPVC",
    category: "UPVC Solutions",
    description: "UPVC frames with realistic wooden texture laminates.",
    imageUrl: "/images/upvc-solutions/wood-finish-upvc.png",
    icon: Layers,
  },
  {
    id: "u5",
    title: "Soundproof Glazing",
    category: "UPVC Solutions",
    description: "Double glazed UPVC units for silence in busy areas.",
    imageUrl: "/images/upvc-solutions/soundproof-glazing.png",
    icon: VolumeX,
  },

  // Fiberglass
  {
    id: "f1",
    title: "Car Parking Sheds",
    category: "Fiberglass Solutions",
    description: "Durable fiberglass parking shades for homes and offices.",
    imageUrl: "/images/fiberglass-solutions/rooftop-fiber-shelters.png",
    icon: Umbrella,
  },
  {
    id: "f2",
    title: "Rooftop Fiber Shelters",
    category: "Fiberglass Solutions",
    description: "Weatherproof fiber rooms for rooftop storage or sitting.",
    imageUrl: "/images/fiberglass-solutions/rooftop-fiber-shelters.png",
    icon: Home,
  },
  {
    id: "f3",
    title: "Industrial Fiber Roofing",
    category: "Fiberglass Solutions",
    description: "Translucent roofing sheets for factories and warehouses.",
    imageUrl: "/images/fiberglass-solutions/industrial-fiber-roofing.png",
    icon: Factory,
  },
  {
    id: "f4",
    title: "Fiberglass Domes",
    category: "Fiberglass Solutions",
    description: "Architectural domes for mosques and entrance halls.",
    imageUrl: "/images/fiberglass-solutions/fiberglass-domes.png",
    icon: Circle,
  },
  {
    id: "f5",
    title: "Fiber Water Tank Covers",
    category: "Fiberglass Solutions",
    description: "Hygienic and durable covers for concrete water tanks.",
    imageUrl: "/images/fiberglass-solutions/fiber-water-tank-covers.png",
    icon: Droplets,
  },

  // Interior & Advanced
  {
    id: "i1",
    title: "Decorative Wall Paneling",
    category: "Interior & Decorative",
    description: "Padded fabric and cotton wall panels for bedrooms.",
    imageUrl: "/images/interior-decorative/window-blinds.png",
    icon: Sofa,
  },
  {
    id: "i2",
    title: "Window Blinds",
    category: "Interior & Decorative",
    description: "Roller, vertical, and venetian blinds for windows.",
    imageUrl: "/images/interior-decorative/window-blinds.png",
    icon: AlignJustify,
  },
  {
    id: "i3",
    title: "Spider Glazing Systems",
    category: "Advanced Solutions",
    description: "Seamless glass curtain walls using spider fittings.",
    imageUrl: "/images/advanced-solutions/spider-glazing-systems.png",
    icon: Building2,
  },
  {
    id: "i4",
    title: "Glass Skylights",
    category: "Advanced Solutions",
    description: "Natural light solutions with structural glass roofs.",
    imageUrl: "/images/advanced-solutions/glass-skylights.png",
    icon: Sun,
  },
  {
    id: "i5",
    title: "Automatic Sliding Doors",
    category: "Advanced Solutions",
    description: "Sensor-operated glass doors for malls and hospitals.",
    imageUrl: "/images/advanced-solutions/automatic-sliding-doors.png",
    icon: MoveHorizontal,
  },
  {
    id: "i6",
    title: "ACP Cladding",
    category: "Advanced Solutions",
    description: "Aluminium Composite Panels for modern building exteriors.",
    imageUrl: "/images/advanced-solutions/acp-cladding.png",
    icon: Layers,
  },

  // Repair
  {
    id: "r1",
    title: "Emergency Glass Repair",
    category: "Repair & Maintenance",
    description: "24/7 replacement of broken windows and doors.",
    imageUrl: "/images/repair-maintenance/glass-polishing.png",
    icon: Wrench,
  },
  {
    id: "r2",
    title: "Door Closer Fixing",
    category: "Repair & Maintenance",
    description: "Repair and adjustment of floor springs and door closers.",
    imageUrl: "/images/repair-maintenance/door-closer-fixing.png",
    icon: Wrench,
  },
  {
    id: "r3",
    title: "Window Leakproofing",
    category: "Repair & Maintenance",
    description: "Silicon sealing to prevent water and dust leakage.",
    imageUrl: "/images/repair-maintenance/window-leakproofing.png",
    icon: Droplets,
  },
  {
    id: "r4",
    title: "Glass Polishing",
    category: "Repair & Maintenance",
    description: "Removal of scratches and stains from existing glass.",
    imageUrl: "/images/repair-maintenance/glass-polishing.png",
    icon: Sparkles,
  },
];

// --- PROJECTS (20 Items) ---
export const projects: ProjectItem[] = [
  {
    id: "p1",
    title: "Bahria Town Luxury Villa",
    location: "Bahria Town, Sector C",
    description: "Full exterior spider glazing and aluminium windows.",
    fullDescription:
      "A modern 1-kanal villa requiring complete exterior glazing. We installed 12mm tempered spider glass for the main facade and soundproof UPVC windows for all bedrooms.",
    client: "Mr. Usman Tariq",
    date: "March 2024",
    servicesUsed: ["Spider Glazing", "UPVC Windows", "Glass Railings"],
    imageUrl: "/luxuryvilla.jpg",
  },
  {
    id: "p2",
    title: "Corporate Office Interiors",
    location: "DHA Phase 6, Lahore",
    description: "12mm glass partitions and automated doors.",
    fullDescription:
      "Designed and installed frameless glass partitions for a software house. Included automated sensor doors for the main entrance and frosted films for meeting rooms.",
    client: "TechSolutions Pvt Ltd",
    date: "January 2024",
    servicesUsed: ["Glass Partitions", "Automatic Doors", "Frosted Film"],
    imageUrl: "/Corporate-Office-Interiors .jpg",
  },
  {
    id: "p3",
    title: "Eiffel Tower Bahria Town Lahore",
    location: "Bahria Town",
    description: "High-rise glass work completed at Eiffel Tower.",
    fullDescription:
      "We successfully completed high-rise glass installation and repair work on the Eiffel Tower structure in Bahria Town Lahore, ensuring durability, safety, and a clean modern finish.",
    client: "Bahria Town",
    date: "December 2023",
    servicesUsed: ["Glass Work", "High-Rise Installation", "Maintenance"],
    imageUrl: "/Eiffel-Tower-Bahria-Town-Lahore.jpg",
  },
  {
    id: "p4",
    title: "Askari 11 Apartments",
    location: "Askari 11, Lahore",
    description: "UPVC windows installation for 50+ units.",
    fullDescription:
      "Large scale project involving the supply and installation of energy-efficient UPVC sliding windows for a new apartment block.",
    client: "Army Housing",
    date: "November 2023",
    servicesUsed: ["UPVC Windows", "Mosquito Nets"],
    imageUrl: "/images/projects/askari-11-apartments.png",
  },
  {
    id: "p5",
    title: "MM Alam Road Boutique",
    location: "Gulberg, Lahore",
    description: "Decorative mirrors and frameless shop front.",
    fullDescription:
      "High-end retail fit-out featuring 12mm clear tempered glass shop front and custom-cut decorative mirrors for the interior.",
    client: "Sapphire Retail",
    date: "October 2023",
    servicesUsed: ["Shop Fronts", "Decorative Mirrors"],
    imageUrl: "/MM-Alam-Road-Boutique.jpg",
  },
  {
    id: "p6",
    title: "Industrial Fiber Shed",
    location: "Sundar Industrial Estate",
    description: "Heavy-duty fiberglass roofing for warehouse.",
    fullDescription:
      "Fabrication and installation of a 5000 sq.ft fiberglass shed structure for raw material storage protection against rain and sun.",
    client: "Packages Ltd",
    date: "September 2023",
    servicesUsed: ["Fiberglass Sheds", "Steel Fabrication"],
    imageUrl: "/Industrial-Fiber-Shed .jpg",
  },
  {
    id: "p7",
    title: "University Campus Glazing",
    location: "Bhira University, Lahore",
    description: "Structural steel and glass corridors.",
    fullDescription:
      "Connecting two academic blocks with a modern steel and glass covered walkway.",
    client: "Bhira University Admin",
    date: "August 2023",
    servicesUsed: ["Structural Steel", "Laminated Glass"],
    imageUrl: "/Bhira-University-Lahore .webp",
  },
  {
    id: "p8",
    title: "Winterland Park",
    location: "Bahria Town, Lahore",
    description: "Specialized thermal glass installations.",
    fullDescription:
      "Installation of specialized multi-layered insulated glass units to maintain sub-zero temperatures inside the park.",
    client: "Winterland Management",
    date: "July 2023",
    servicesUsed: ["Insulated Glass", "Thermal Break Aluminium"],
    imageUrl: "/Winterland-Park.jpg",
  },
  {
    id: "p9",
    title: "Ary Studios Soundproofing",
    location: "Bahria Town, Lahore",
    description: "Acoustic glass paneling for studios.",
    fullDescription:
      "High-performance acoustic glazing to ensure complete sound isolation for recording studios.",
    client: "ARY Network",
    date: "June 2023",
    servicesUsed: ["Acoustic Glass", "Aluminium Partitions"],
    imageUrl: "/Ary-studios.webp",
  },
  {
    id: "p10",
    title: "Motorway Toll Plaza",
    location: "Lahore-Islamabad Motorway",
    description: "Steel structure and glass canopy.",
    fullDescription:
      "Heavy steel fabrication and toughened glass canopy installation for toll booths.",
    client: "NHA",
    date: "May 2023",
    servicesUsed: ["Steel Fabrication", "Toughened Glass"],
    imageUrl: "/Motorway-Toll-Plaza.jpg",
  },
  {
    id: "p11",
    title: "Valencia Town Residence",
    location: "Valencia Town, Lahore",
    description: "Complete UPVC window solution.",
    fullDescription:
      "Replaced old aluminium windows with modern, energy-efficient UPVC sliding windows.",
    client: "Mrs. Farida Khan",
    date: "April 2023",
    servicesUsed: ["UPVC Windows"],
    imageUrl: "/Valencia-Town-Residence.avif",
  },
  {
    id: "p12",
    title: "Zaitoon Colony Commercial",
    location: "Zaitoon Colony",
    description: "Aluminium cladding and glass facade.",
    fullDescription:
      "Modernization of a commercial plaza face with silver ACP cladding and blue reflective glass.",
    client: "Zaitoon Developers",
    date: "March 2023",
    servicesUsed: ["ACP Cladding", "Reflective Glass"],
    imageUrl: "/Zaitoon-Colony-Commercial.avif",
  },
  {
    id: "p13",
    title: "Fazaia Housing Gym",
    location: "Fazaia Housing, Lahore",
    description: "Large mirrors and shower partitions.",
    fullDescription:
      "Installed wall-to-wall gym mirrors and glass shower enclosures in the changing rooms.",
    client: "Fazaia Club",
    date: "February 2023",
    servicesUsed: ["Wall Mirrors", "Shower Cabins"],
    imageUrl: "/FazaiaHousingGym.jpg",
  },
  {
    id: "p14",
    title: "Lake City Villa",
    location: "Lake City, Lahore",
    description: "Custom fiberglass car parking shed.",
    fullDescription:
      "Designed a cantilever fiberglass shed for 3 cars matching the house aesthetics.",
    client: "Mr. Sohail",
    date: "January 2023",
    servicesUsed: ["Fiberglass Shed"],
    imageUrl: "/lake-city.avif",
  },
  {
    id: "p16",
    title: "Medical Center Entrance",
    location: "Johar Town",
    description: "Automatic sliding glass doors.",
    fullDescription:
      "Installed hygiene-friendly touchless automatic sliding doors for the main patient entrance.",
    client: "Doctors Hospital",
    date: "November 2022",
    servicesUsed: ["Automatic Doors"],
    imageUrl: "/Medical-Center-Entrance.jpg",
  },
  {
    id: "p18",
    title: "Bahria Mosque",
    location: "Bahria Orchard",
    description: "Fiberglass dome and window grills.",
    fullDescription:
      "Fabrication of a decorative fiberglass dome and aluminium safety grills for windows.",
    client: "Mosque Committee",
    date: "September 2022",
    servicesUsed: ["Fiberglass Dome", "Safety Grills"],
    imageUrl: "/Bahria-Mosque.jpg",
  },
  {
    id: "p19",
    title: "Packages Mall Kiosks",
    location: "Walton Road",
    description: "Glass display counters.",
    fullDescription: "UV bonded glass display counters for jewelry kiosks.",
    client: "Various Tenants",
    date: "August 2022",
    servicesUsed: ["UV Bonding", "Display Glass"],
    imageUrl: "/Packages-Mall-Kiosks.jpg",
  },
];

// --- TEAM (6 Items) ---
export const team: TeamMember[] = [
  {
    id: "t1",
    name: "Asif Munir",
    role: "CEO & Founder",
    bio: "20 years of leadership in Pakistan’s glass and aluminium industry. Expert in large-scale commercial facades.",
    imageUrl: "/images/team/asif-munir.png",
  },
  {
    id: "t2",
    name: "Tanzeel Ahmad",
    role: "Project Director",
    bio: "Civil engineer specializing in structural glazing and high-rise installations in Bahria Town.",
    imageUrl: "/images/team/tanzeel-ahmad.png",
  },
  {
    id: "t3",
    name: "Abrar Hussain",
    role: "Head of Fabrication",
    bio: "Master craftsman in aluminium and steel joinery with 15 years of hands-on experience.",
    imageUrl: "/images/team/abrar-hussain.png",
  },
  {
    id: "t4",
    name: "Shahzad Munir",
    role: "Interior Design Lead",
    bio: "Creative visionary for decorative glass, wall paneling, and modern residential interiors.",
    imageUrl: "/images/team/shahzad-munir.png",
  },
  {
    id: "t5",
    name: "Muzafar Hussain",
    role: "Site Supervisor (DHA)",
    bio: "Ensures quality control and timely delivery for all our DHA and Cantt projects.",
    imageUrl: "/images/team/muzafar-hussain.png",
  },
  {
    id: "t6",
    name: "Hafiz Ahmad",
    role: "Senior Technician",
    bio: "Specialist in automatic door systems and sensor glass installations.",
    imageUrl: "/images/team/hafiz-ahmad.png",
  },
];

// --- PRODUCTS (8 Items) ---
export const products: ProductItem[] = [
  {
    id: "prod1",
    name: "Tempered Glass 12mm",
    category: "Glass",
    specs: "12mm thickness, impact resistant",
    description: "High-grade safety glass for partitions and doors.",
    imageUrl: "/Tempered-Glass-12mm.jpg",
  },
  {
    id: "prod2",
    name: "Aluminium Sliding Profile",
    category: "Aluminium",
    specs: "Series 2000, Powder Coated",
    description: "Durable aluminium profiles for window fabrication.",
    imageUrl: "/Aluminum-Sliding-Profile .jpg",
  },
  {
    id: "prod3",
    name: "UPVC Window Frame",
    category: "UPVC",
    specs: "Double Glazed Ready, White",
    description: "Energy efficient frames ensuring thermal insulation.",
    imageUrl: "/UPVC-Window-Frame .jpg",
  },
  {
    id: "prod4",
    name: "Fiberglass Sheet",
    category: "Fiberglass",
    specs: "2mm - 5mm, UV Protected",
    description: "Corrugated and plain sheets for roofing.",
    imageUrl: "/Fiberglass-Sheet.jpg",
  },
  {
    id: "prod5",
    name: "Spider Fittings (SS)",
    category: "Hardware",
    specs: "304 Grade Stainless Steel",
    description: "Heavy duty fittings for structural glazing.",
    imageUrl: "/Spider-Fittings-(SS).jpg",
  },
  {
    id: "prod6",
    name: "Door Closer Machine",
    category: "Hardware",
    specs: "Hydraulic, Floor Spring",
    description: "Smooth operating machines for glass doors.",
    imageUrl: "/Door-Closer-Machine.jpg",
  },
  {
    id: "prod7",
    name: "Frosted Glass Film",
    category: "Decorative",
    specs: "Self-adhesive, Patterned",
    description: "Privacy films for office partitions.",
    imageUrl: "/Frosted-Glass-Film.jpg",
  },
  {
    id: "prod8",
    name: "Silicon Sealant",
    category: "Adhesives",
    specs: "Weatherproof, Clear/Black",
    description: "Industrial grade sealant for glass waterproofing.",
    imageUrl: "/Silicon-Sealant.jpg",
  },
];
